In [1]:
import numpy as np 
import pandas as pd     
path = "/home/lisa/Arupreza/UIDS-II/Input_data/"

In [2]:
Kia_AF = pd.read_csv(path + "Kia_AF.csv")

Kia_DoS_H = pd.read_csv(path + "Kia_DoS_H.csv")
Kia_DoS_M = pd.read_csv(path + "Kia_DoS_M.csv")
Kia_DoS_L = pd.read_csv(path + "Kia_DoS_L.csv")
Kia_DoS_R = pd.read_csv(path + "Kia_DoS_R.csv")

Kia_Fuzz_H = pd.read_csv(path + "Kia_Fuzz_H.csv")
Kia_Fuzz_M = pd.read_csv(path + "Kia_Fuzz_M.csv")
Kia_Fuzz_L = pd.read_csv(path + "Kia_Fuzz_L.csv")
Kia_Fuzz_R = pd.read_csv(path + "Kia_Fuzz_R.csv")

Kia_Rep_H = pd.read_csv(path + "Kia_Rep_H.csv")
Kia_Rep_M = pd.read_csv(path + "Kia_Rep_M.csv")
Kia_Rep_L = pd.read_csv(path + "Kia_Rep_L.csv")
Kia_Rep_R = pd.read_csv(path + "Kia_Rep_R.csv")

In [6]:
Kia_AF

,Time_Offset,CAN_ID,Data_Length,One,Two,Three,Four,Five,Six,Seven,Eight,Label
0,16.0,0340,8,0F,00,D5,2B,FC,00,2A,1A,Normal
1,17.3,0251,8,DC,23,C8,12,00,E4,37,7F,Normal
2,17.5,02B0,6,EF,FF,00,07,E8,14,-1,-1,Normal
3,17.9,0153,8,20,80,10,FF,00,FF,80,2E,Normal
4,18.0,0164,4,00,08,02,91,-1,-1,-1,-1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...
690020,228123.8,0260,8,03,31,2A,30,0D,D1,A7,77,Normal
690021,228124.0,0368,8,07,00,00,00,07,00,00,60,Normal
690022,228124.2,0329,8,E3,B0,80,0C,11,34,16,10,Normal
690023,228124.5,0436,4,00,00,00,08,-1,-1,-1,-1,Normal
690024,228124.7,0153,8,20,80,10,FF,00,FF,C0,6E,Normal

In [10]:
Kia_DoS_R

,Time_Offset,CAN_ID,Data_Length,One,Two,Three,Four,Five,Six,Seven,...,Label,Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Time_Gap
0,16.000000,0340,8,0F,00,D5,2B,FC,00,2A,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,16.088901,0000,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,DoS,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,0.088901
2,17.300000,0251,8,DC,23,C8,12,00,E4,37,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.211099
3,17.500000,02B0,6,EF,FF,00,07,E8,14,-1,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000
4,17.900000,0153,8,20,80,10,FF,00,FF,80,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793895,228123.800000,0260,8,03,31,2A,30,0D,D1,A7,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000
793896,228124.000000,0368,8,07,00,00,00,07,00,00,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000
793897,228124.200000,0329,8,E3,B0,80,0C,11,34,16,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000
793898,228124.500000,0436,4,00,00,00,08,-1,-1,-1,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000
793899,228124.700000,0153,8,20,80,10,FF,00,FF,C0,...,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000

In [17]:
import numpy as np 
import pandas as pd     
path = "/home/lisa/Arupreza/UIDS-II/Input_data/"

Kia_AF = pd.read_csv(path + "Kia_AF.csv")
Tesla_AF = pd.read_csv(path + "Tesla_AF.csv")
Sil_AF = pd.read_csv(path + "Sil_AF.csv")
Gen_AF = pd.read_csv(path + "Gen_AF.csv")

/tmp/ipykernel_1874476/1734038923.py:8: DtypeWarning: Columns (20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  Gen_AF = pd.read_csv(path + "Gen_AF.csv")

In [18]:
print(Tesla_AF['Label'].value_counts())
print(Sil_AF['Label'].value_counts())
print(Gen_AF['Label'].value_counts())
print(Kia_AF['Label'].value_counts())

Label
Normal    600000
Name: count, dtype: int64
Label
Normal    600000
Name: count, dtype: int64
Label
0    600000
Name: count, dtype: int64
Label
Normal    600000
Name: count, dtype: int64

In [ ]:
from DataGenSrc.RandomCANFreq import CANDataInjectionCountFreq
clean_original_df = Tesla_AF[Tesla_AF['Label'] == 'Normal'].copy()

# NOW, run the injection function on the CLEAN DataFrame.
final_result_df = CANDataInjectionCountFreq(
    type_of_attack="DoS",
    orig_df=clean_original_df,  # Use the filtered, clean data
    group_size=30 
)

Injecting 'DoS' messages...
Generated 90362 'DoS' messages for injection.

In [ ]:
from DataGenSrc.RandomCANFreq import CANDataInjectionCountFreq
clean_original_df = Sil_AF[Sil_AF['Label'] == 'Normal'].copy()
# 4. Inject a Replay attack
final_result_df = CANDataInjectionCountFreq(
    type_of_attack="Replay",
    orig_df=clean_original_df.copy(), # Inject into the DoS-infected log
    injection_df=clean_original_df[:300000],
    group_size=30
)

Injecting 'Replay' messages sequentially...
Generated 90149 'Replay' messages for injection.

In [47]:
final_result_df[final_result_df['Label']=='Replay']

,Time_Offset,CAN_ID,Data_Length,One,Two,Three,Four,Five,Six,Seven,Eight,Label
4,6.792422,0189,8,8F,FF,0F,FF,2F,FF,FF,F0,Replay
12,8.856904,0185,2,1B,FC,-1,-1,-1,-1,-1,-1,Replay
14,9.977257,01C7,7,09,70,F6,8D,00,00,3F,-1,Replay
16,10.197679,01FC,8,FF,98,FF,30,00,00,03,05,Replay
21,11.857593,01C6,8,2C,D3,2C,A8,00,03,4D,60,Replay
...,...,...,...,...,...,...,...,...,...,...,...,...
690103,233376.201890,00D0,8,80,00,80,00,80,00,80,00,Replay
690116,233378.508263,01C7,7,09,70,36,90,00,00,3F,-1,Replay
690122,233379.721369,01C4,8,4A,62,C7,41,04,00,05,FE,Replay
690141,233388.486218,0185,2,1B,FC,-1,-1,-1,-1,-1,-1,Replay
690143,233388.794778,01C3,8,07,FA,07,FD,00,10,32,03,Replay

In [48]:
final_result_df.to_csv("Sil_Rep_R.csv", index=False)

In [51]:
from DataGenSrc.CANFDFuzzCorrected import CANFDDataInjection

fuzz_injected_df = CANFDDataInjection("Fuzz", Gen_AF)

ImportError: cannot import name 'CANFDDataInjection' from 'DataGenSrc.CANFDFuzzCorrected' (/home/lisa/Arupreza/UIDS-II/DataGenSrc/CANFDFuzzCorrected.py)